### ISSUE TITLE
bad argument

### ISSUE THREAD

**Issue by lloscarll** [Jonesad-ETSU/awesomewm-config#9]
![VirtualBox_Arch-ETSU_22_03_2022_06_38_22](https://user-images.githubusercontent.com/16115396/159380542-0695280c-8523-49ec-ab32-1ae37e451364.png)

error on archchart.lua:50: bad argument #1 to 'floor' (number excepted, got nil)

**Comment by Jonesad-ETSU** [comment]
Hey, so to fix this the first thing to ask is do you have mpstat installed?
If so, can you provide screenshots of the outputs of the following commands:

`mpstat | awk '{if(NF>=13 && $13 ~ /[[:digit:]]/) print 100-$13}'`
and
`free -m | awk 'NF==7 {print $3/$2*100}'`

If one of those two produces no output or errors out (aka. mpstat isn't installed), that is definitely the issue. Assuming you are using arch linux, you can install mpstat by installing the following package: `sysstat`. The full command is: `sudo pacman -Sy sysstat`.

Note: You can follow these steps from any Window Manager or Desktop Environment. It doesn't matter.
